### ISSUE TITLE
problems with examples at DA_paper/training/explicit

### ISSUE THREAD

**Issue by physorgchem** [duartegroup/mlp-train#56]
Dear developers,

This is a question for the example at https://github.com/Hanwen1018/mlp-train Sorry that I could not ask questions in the other fork. 

We have some difficulty running the example at DA_paper/training/explicit with the following error:
Traceback (most recent call last):
  File "endo_ace_ex.py", line 246, in <module>
    TS=False)
  File "endo_ace_ex.py", line 193, in generate_init_configs
    TS.load(filename = 'cis_endo_TS_wB97M.xyz', box=None)
AttributeError: 'Configuration' object has no attribute 'load'

It seems that there is no load in Configuration, but there is a load_xyz inside Configuration.Set.

Could you please have a look? We were able to run the implicit training, so the installation should be correct. Appreciate your help.

**Comment by physorgchem** [comment]
thanks @Hanwen1018 for your quick response. 

However, I met the following error:
```
File "endo_ace_ex.py", line 246, in <module>
    TS=False)
File "endo_ace_ex.py", line 193, in generate_init_configs
    TS.load_xyz(filename = 'cis_endo_TS_wB97M.xyz', box=Box([11, 11, 11]))
TypeError: load_xyz() missing 2 required positional arguments: 'charge' and 'mult'
```

It seems ConfigurationSet.load_xyz need charge and multiplicity. 

After attempting to fix it, 
```TS.load_xyz(filename = 'cis_endo_TS_wB97M.xyz', charge=0, mult=1, box=Box([11, 11, 11]))```

I had a new error:
```
  File "endo_ace_ex.py", line 246, in <module>
    TS=False)
  File "endo_ace_ex.py", line 205, in generate_init_configs
    radius=1.7)
  File "endo_ace_ex.py", line 113, in solvation
    assert solvent_config.box != None, 'configuration must have box'
AssertionError: configuration must have box
```
