### ISSUE TITLE
Charge, mult error in DA_papers/training/explicit

### ISSUE THREAD

**Issue by tanoury1** [duartegroup/mlp-train#76]
Hi,
Not sure if this is similar to #57:
After activating mlptrain-ace, I went to test with DA_papers/training/explicit.  I got the following output/error:

(mlptrain-ace) [tanoury@hpcnode70:explicit]$ python endo_ace_ex.py 
2023-12-06 08:43:49 hpcnode70 autode.log.log[19499] INFO Generating a Molecule object for h2o.xyz
2023-12-06 08:43:49 hpcnode70 autode.log.log[19499] INFO Generating species from .xyz file
2023-12-06 08:43:49 hpcnode70 autode.log.log[19499] INFO Getting atoms from h2o.xyz
2023-12-06 08:43:49 hpcnode70 autode.log.log[19499] INFO Geometry changed- resetting energies of h2o.xyz
2023-12-06 08:43:49 hpcnode70 autode.log.log[19499] INFO Generating molecular graph with NetworkX
2023-12-06 08:43:49 hpcnode70 autode.log.log[19499] INFO Setting the π bonds in a species
2023-12-06 08:43:49 hpcnode70 autode.log.log[19499] INFO Setting the stereocentres in a species
2023-12-06 08:43:49 hpcnode70 autode.log.log[19499] INFO Generating a Molecule object for cis_endo_TS_wB97M.xyz
2023-12-06 08:43:49 hpcnode70 autode.log.log[19499] INFO Generating species from .xyz file
2023-12-06 08:43:49 hpcnode70 autode.log.log[19499] INFO Getting atoms from cis_endo_TS_wB97M.xyz
2023-12-06 08:43:49 hpcnode70 autode.log.log[19499] INFO Geometry changed- resetting energies of cis_endo_TS_wB97M.xyz
2023-12-06 08:43:49 hpcnode70 autode.log.log[19499] INFO Generating molecular graph with NetworkX
2023-12-06 08:43:49 hpcnode70 autode.log.log[19499] INFO Setting the π bonds in a species
2023-12-06 08:43:49 hpcnode70 autode.log.log[19499] INFO Setting the stereocentres in a species
Traceback (most recent call last):
  File "/cluster/home/tanoury/Duarte-codes/mlp-train/examples/DA_paper/training/explicit/endo_ace_ex.py", line 246, in <module>
    water_init = generate_init_configs(n=10, 
  File "/cluster/home/tanoury/Duarte-codes/mlp-train/examples/DA_paper/training/explicit/endo_ace_ex.py", line 191, in generate_init_configs
    TS.load_xyz(filename = 'cis_endo_TS_wB97M.xyz')
TypeError: load_xyz() missing 2 required positional arguments: 'charge' and 'mult'

Best regards,
Jerry

**Comment by juraskov** [comment]
Hi Jerry, thanks for the report. We corrected the examples and closed the issue.

Veronika
