### ISSUE TITLE
AssertionError: configuration must have box

### ISSUE THREAD

**Issue by tanoury1** [duartegroup/mlp-train#79]
Hi, 
Getting closer.  I make the changes as described in 02bfbb1.  The code ran a bit further, but running into another error:

2023-12-07 08:21:45 hpcnode80 mlptrain.log[190726] INFO Randomised in 7 iterations
Traceback (most recent call last):
  File "/cluster/home/tanoury/Duarte-codes/mlp-train/examples/DA_paper/training/explicit/endo_ace_ex.py", line 246, in <module>
    water_init = generate_init_configs(n=10, 
  File "/cluster/home/tanoury/Duarte-codes/mlp-train/examples/DA_paper/training/explicit/endo_ace_ex.py", line 204, in generate_init_configs
    solvated = solvation (solute_config=TS,
  File "/cluster/home/tanoury/Duarte-codes/mlp-train/examples/DA_paper/training/explicit/endo_ace_ex.py", line 111, in solvation
    assert solvent_config.box is not None, 'configuration must have box'
AssertionError: configuration must have box

Jerry

**Comment by juraskov** [comment]
Dear Jerry, we apologise for this and thanks for your patience with testing. I fixed this issue in #80. Could you please modify your code accordingly before the PR is approved?

Thanks

Veronika

**Comment by juraskov** [comment]
Issue solved in PR #80.
