### ISSUE TITLE
Running DA_paper examples: successes and errors

### ISSUE THREAD

**Issue by tanoury1** [duartegroup/mlp-train#81]
Hi,
I'm running through the full set of DA_paper examples from a successfully built mlptrain-ace environment.  Here are my results so far:

- training/implicit worked marvelously.  The calculation went to completion.
- training/explicit is running without any issues so far.
- uphill.py and pes.py error out with:
Traceback (most recent call last):
  File "/cluster/home/tanoury/Duarte-codes/mlp-train/examples/DA_paper/2D_pes/pes.py", line 12, in <module>
    from mlptrain.md import _convert_ase_traj
ModuleNotFoundError: No module named 'mlptrain.md'

- fes.py (in 1d_fes) errors out due to not finding 'endo_in_water_ace_wB97M.json':The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/cluster/home/tanoury/Duarte-codes/mlp-train/examples/DA_paper/1d_fes/fes.py", line 40, in <module>
    us.run_umbrella_sampling(irc,
  File "/cluster/home/tanoury/Duarte-codes/mlp-train/mlptrain/sampling/umbrella.py", line 454, in run_umbrella_sampling
    window_traj = window_process.get()
  File "/cluster/home/tanoury/miniconda3/envs/mlptrain-ace/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
julia.core.JuliaError: Exception 'SystemError: opening file "./endo_in_water_ace_wB97M.json": No such file or directory' occurred while calling julia code:
D = load_dict("./endo_in_water_ace_wB97M.json")

All the best,
Jerry

**Comment by tanoury1** [comment]
Hi, 
Still plugging away at running your code in my environment.  
I was able to get around some of the above errors by editing some of the scripts on my own copy (not sure if the specific workaround/edits are the correct way to address the errors??).
- I was able to fix the uphill.py and pes.py errors by copying md.py from mlptrain/sampling directory ro mlptrain directory.  pes.py then gave me another error: 
File "/cluster/home/tanoury/Duarte-codes/
[explicit_training_error.txt](https://github.com/duartegroup/mlp-train/files/13730190/explicit_training_error.txt)
[explicit_training_error.txt](https://github.com/duartegroup/mlp-train/files/13730200/explicit_training_error.txt)
mlp-train/examples/DA_paper/2D_pes/pes.py", line 256, in <module>
    @mlt.utils.work_in_tmp_dir(copied_exts=['.xml', '.json'])
TypeError: work_in_tmp_dir() got an unexpected keyword argument 'copied_exts'

I was able to fix this by changing 'copied_exts' to 'copied_substring'

After I made these changes, the subsequent errors were:
julia.core.JuliaError: Exception 'SystemError: opening file "./endo_in_water_ace_wB97M.json": No such file or directory' occurred while calling julia code:
D = load_dict("./endo_in_water_ace_wB97M.json")

I presume this json file would be the actual mlp from the explicit training.

-  Upon trying  endo_ace_ex.py ( located in DA_paper/training/explicit) again, got a long error readout.  See attached file.

All the best,
Jerry
